#pragma once
#define GRID_SIZE 15
#define NODE_SIZE 50.0f
#define GRID_SPACING 6.0f
#define EDGE_THICKNESS 2.0f
#define COST 10
#define COST_DIAGONAL 14
#define COST_HORVER 10
#define COST_HEURISTIC_HORVER 11
#define COST_HEURISTIC_DIAGONAL 15
#define PLAYER_SPEED 500.0f